name: Build app and deploy to aliyun

on:
 push:
  branches:
  - master
jobs:
 build:
  # runs-on 指定job任务运⾏所需要的虚拟机环境(必填字段)
  runs-on: ubuntu-latest
  steps:
    # 获取源码
    - name: Checkout
      # 使⽤action库 actions/checkout获取源码
      uses: actions/checkout@master
    # 安装Node13
    - name: use Node.js 13.8.0
      # 使⽤action库 actions/setup-node安装node
      uses: actions/setup-node@v1
      with:
        node-version: 13.8.0
    # 安装依赖
    - name: Yarn install
      run: npm install yarn && yarn install
    # 打包
    - name: Yarn build
      run: yarn run build:prod
    # 部署到阿⾥云
    - name: Deploy to Aliyun
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        # 私钥
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        # scp参数
        ARGS: "-avzr --delete"
        # 源⽬录
        SOURCE: "dist"
        # 服务器ip：换成你的服务器IP
        REMOTE_HOST: "47.116.66.143"
        # ⽤户
        REMOTE_USER: "root"
        # ⽬标地址
        TARGET: "/root/konor-admin/client"